name: Create Extension Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Build extension
      run: |
        chmod +x build.sh
        ./build.sh
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: ArXiv to Blog Extension v${{ steps.get_version.outputs.VERSION }}
        body: |
          ## 🚀 ArXiv to Blog Extension v${{ steps.get_version.outputs.VERSION }}
        files: |
          dist/arxiv-to-alphaxiv-v${{ steps.get_version.outputs.VERSION }}.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
